### ISSUE TITLE
Shortcuts aren't working MacOS Sierra

### ISSUE THREAD

**Issue by chef-danny-d** [inns/mak-mini#4]
For some reason I can't seem to be able to user CMD + C or CMD + V to copy and paste. This occurred both on the online and the mini versions. 

Let me know if I'm doing something wrong or if this is a known issue. 

Thanks.

**Comment by quietshu** [comment]
Thank you for reporting! 

I think I've seen this bug before but my very recent updates should have fixed this problem. But there might be some JS cache issue that the browser still use the old scripts. I've already changed the cache strategy to expire after 10min (it was 8 days before changed). 

So for mak.ink, __use <kbd>CMD+Shift+R</kbd> to do a full refresh__. But for Mak mini currently it doesn't provide a way to clean the cache. I will add a `update` button later to handle App update & reset HTTP cache.

Let me know if it doesn't work :0

**Comment by chef-danny-d** [comment]
The latest update fixed it for me. Just had to hard refresh it. 

Thank you !!!

**Comment by quietshu** [comment]
Cooool!
